declare const useStyle: (href: string, properties?: {
    as?: string | undefined;
    charset?: string | undefined;
    crossOrigin?: string | null | undefined;
    disabled?: boolean | undefined;
    href?: string | undefined;
    hreflang?: string | undefined;
    imageSizes?: string | undefined;
    imageSrcset?: string | undefined;
    integrity?: string | undefined;
    media?: string | undefined;
    referrerPolicy?: string | undefined;
    rel?: string | undefined;
    readonly relList?: DOMTokenList | undefined;
    rev?: string | undefined;
    readonly sizes?: DOMTokenList | undefined;
    target?: string | undefined;
    type?: string | undefined;
    addEventListener?: {
        <K extends "input" | "progress" | "select" | "reset" | "error" | "cancel" | "click" | "fullscreenchange" | "fullscreenerror" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | "auxclick" | "blur" | "canplay" | "canplaythrough" | "change" | "close" | "contextmenu" | "cuechange" | "dblclick" | "drag" | "dragend" | "dragenter" | "dragexit" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "ended" | "focus" | "focusin" | "focusout" | "gotpointercapture" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadstart" | "lostpointercapture" | "mousedown" | "mouseenter" | "mouseleave" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "pause" | "play" | "playing" | "pointercancel" | "pointerdown" | "pointerenter" | "pointerleave" | "pointermove" | "pointerout" | "pointerover" | "pointerup" | "ratechange" | "resize" | "scroll" | "securitypolicyviolation" | "seeked" | "seeking" | "selectionchange" | "selectstart" | "stalled" | "submit" | "suspend" | "timeupdate" | "toggle" | "touchcancel" | "touchend" | "touchmove" | "touchstart" | "transitioncancel" | "transitionend" | "transitionrun" | "transitionstart" | "volumechange" | "waiting" | "wheel" | "copy" | "cut" | "paste">(type: K, listener: (this: HTMLLinkElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void;
    } | undefined;
    removeEventListener?: {
        <K_1 extends "input" | "progress" | "select" | "reset" | "error" | "cancel" | "click" | "fullscreenchange" | "fullscreenerror" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | "auxclick" | "blur" | "canplay" | "canplaythrough" | "change" | "close" | "contextmenu" | "cuechange" | "dblclick" | "drag" | "dragend" | "dragenter" | "dragexit" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "ended" | "focus" | "focusin" | "focusout" | "gotpointercapture" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadstart" | "lostpointercapture" | "mousedown" | "mouseenter" | "mouseleave" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "pause" | "play" | "playing" | "pointercancel" | "pointerdown" | "pointerenter" | "pointerleave" | "pointermove" | "pointerout" | "pointerover" | "pointerup" | "ratechange" | "resize" | "scroll" | "securitypolicyviolation" | "seeked" | "seeking" | "selectionchange" | "selectstart" | "stalled" | "submit" | "suspend" | "timeupdate" | "toggle" | "touchcancel" | "touchend" | "touchmove" | "touchstart" | "transitioncancel" | "transitionend" | "transitionrun" | "transitionstart" | "volumechange" | "waiting" | "wheel" | "copy" | "cut" | "paste">(type: K_1, listener: (this: HTMLLinkElement, ev: HTMLElementEventMap[K_1]) => any, options?: boolean | EventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions | undefined): void;
    } | undefined;
    accessKey?: string | undefined;
    readonly accessKeyLabel?: string | undefined;
    autocapitalize?: string | undefined;
    dir?: string | undefined;
    draggable?: boolean | undefined;
    hidden?: boolean | undefined;
    innerText?: string | undefined;
    lang?: string | undefined;
    readonly offsetHeight?: number | undefined;
    readonly offsetLeft?: number | undefined;
    readonly offsetParent?: Element | null | undefined;
    readonly offsetTop?: number | undefined;
    readonly offsetWidth?: number | undefined;
    spellcheck?: boolean | undefined;
    title?: string | undefined;
    translate?: boolean | undefined;
    click?: (() => void) | undefined;
    readonly assignedSlot?: HTMLSlotElement | null | undefined;
    readonly attributes?: NamedNodeMap | undefined;
    readonly classList?: DOMTokenList | undefined;
    className?: string | undefined;
    readonly clientHeight?: number | undefined;
    readonly clientLeft?: number | undefined;
    readonly clientTop?: number | undefined;
    readonly clientWidth?: number | undefined;
    id?: string | undefined;
    readonly localName?: string | undefined;
    readonly namespaceURI?: string | null | undefined;
    onfullscreenchange?: ((this: Element, ev: Event) => any) | null | undefined;
    onfullscreenerror?: ((this: Element, ev: Event) => any) | null | undefined;
    outerHTML?: string | undefined;
    readonly ownerDocument?: Document | undefined;
    readonly prefix?: string | null | undefined;
    readonly scrollHeight?: number | undefined;
    scrollLeft?: number | undefined;
    scrollTop?: number | undefined;
    readonly scrollWidth?: number | undefined;
    readonly shadowRoot?: ShadowRoot | null | undefined;
    slot?: string | undefined;
    readonly tagName?: string | undefined;
    attachShadow?: ((init: ShadowRootInit) => ShadowRoot) | undefined;
    closest?: {
        <K_2 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(selector: K_2): HTMLElementTagNameMap[K_2] | null;
        <K_3 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(selector: K_3): SVGElementTagNameMap[K_3] | null;
        <E extends Element = Element>(selector: string): E | null;
    } | undefined;
    getAttribute?: ((qualifiedName: string) => string | null) | undefined;
    getAttributeNS?: ((namespace: string | null, localName: string) => string | null) | undefined;
    getAttributeNames?: (() => string[]) | undefined;
    getAttributeNode?: ((name: string) => Attr | null) | undefined;
    getAttributeNodeNS?: ((namespaceURI: string, localName: string) => Attr | null) | undefined;
    getBoundingClientRect?: (() => DOMRect) | undefined;
    getClientRects?: (() => DOMRectList) | undefined;
    getElementsByClassName?: ((classNames: string) => HTMLCollectionOf<Element>) | undefined;
    getElementsByTagName?: {
        <K_4 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(qualifiedName: K_4): HTMLCollectionOf<HTMLElementTagNameMap[K_4]>;
        <K_5 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(qualifiedName: K_5): HTMLCollectionOf<SVGElementTagNameMap[K_5]>;
        (qualifiedName: string): HTMLCollectionOf<Element>;
    } | undefined;
    getElementsByTagNameNS?: {
        (namespaceURI: "http://www.w3.org/1999/xhtml", localName: string): HTMLCollectionOf<HTMLElement>;
        (namespaceURI: "http://www.w3.org/2000/svg", localName: string): HTMLCollectionOf<SVGElement>;
        (namespaceURI: string, localName: string): HTMLCollectionOf<Element>;
    } | undefined;
    hasAttribute?: ((qualifiedName: string) => boolean) | undefined;
    hasAttributeNS?: ((namespace: string | null, localName: string) => boolean) | undefined;
    hasAttributes?: (() => boolean) | undefined;
    hasPointerCapture?: ((pointerId: number) => boolean) | undefined;
    insertAdjacentElement?: ((position: InsertPosition, insertedElement: Element) => Element | null) | undefined;
    insertAdjacentHTML?: ((where: InsertPosition, html: string) => void) | undefined;
    insertAdjacentText?: ((where: InsertPosition, text: string) => void) | undefined;
    matches?: ((selectors: string) => boolean) | undefined;
    msGetRegionContent?: (() => any) | undefined;
    releasePointerCapture?: ((pointerId: number) => void) | undefined;
    removeAttribute?: ((qualifiedName: string) => void) | undefined;
    removeAttributeNS?: ((namespace: string | null, localName: string) => void) | undefined;
    removeAttributeNode?: ((attr: Attr) => Attr) | undefined;
    requestFullscreen?: ((options?: FullscreenOptions | undefined) => Promise<void>) | undefined;
    requestPointerLock?: (() => void) | undefined;
    scroll?: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    } | undefined;
    scrollBy?: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    } | undefined;
    scrollIntoView?: ((arg?: boolean | ScrollIntoViewOptions | undefined) => void) | undefined;
    scrollTo?: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    } | undefined;
    setAttribute?: ((qualifiedName: string, value: string) => void) | undefined;
    setAttributeNS?: ((namespace: string | null, qualifiedName: string, value: string) => void) | undefined;
    setAttributeNode?: ((attr: Attr) => Attr | null) | undefined;
    setAttributeNodeNS?: ((attr: Attr) => Attr | null) | undefined;
    setPointerCapture?: ((pointerId: number) => void) | undefined;
    toggleAttribute?: ((qualifiedName: string, force?: boolean | undefined) => boolean) | undefined;
    webkitMatchesSelector?: ((selectors: string) => boolean) | undefined;
    readonly baseURI?: string | undefined;
    readonly childNodes?: NodeListOf<ChildNode> | undefined;
    readonly firstChild?: ChildNode | null | undefined;
    readonly isConnected?: boolean | undefined;
    readonly lastChild?: ChildNode | null | undefined;
    readonly nextSibling?: ChildNode | null | undefined;
    readonly nodeName?: string | undefined;
    readonly nodeType?: number | undefined;
    nodeValue?: string | null | undefined;
    readonly parentElement?: HTMLElement | null | undefined;
    readonly parentNode?: (Node & ParentNode) | null | undefined;
    readonly previousSibling?: ChildNode | null | undefined;
    textContent?: string | null | undefined;
    appendChild?: (<T extends Node>(newChild: T) => T) | undefined;
    cloneNode?: ((deep?: boolean | undefined) => Node) | undefined;
    compareDocumentPosition?: ((other: Node) => number) | undefined;
    contains?: ((other: Node | null) => boolean) | undefined;
    getRootNode?: ((options?: GetRootNodeOptions | undefined) => Node) | undefined;
    hasChildNodes?: (() => boolean) | undefined;
    insertBefore?: (<T_1 extends Node>(newChild: T_1, refChild: Node | null) => T_1) | undefined;
    isDefaultNamespace?: ((namespace: string | null) => boolean) | undefined;
    isEqualNode?: ((otherNode: Node | null) => boolean) | undefined;
    isSameNode?: ((otherNode: Node | null) => boolean) | undefined;
    lookupNamespaceURI?: ((prefix: string | null) => string | null) | undefined;
    lookupPrefix?: ((namespace: string | null) => string | null) | undefined;
    normalize?: (() => void) | undefined;
    removeChild?: (<T_2 extends Node>(oldChild: T_2) => T_2) | undefined;
    replaceChild?: (<T_3 extends Node>(newChild: Node, oldChild: T_3) => T_3) | undefined;
    readonly ATTRIBUTE_NODE?: number | undefined;
    readonly CDATA_SECTION_NODE?: number | undefined;
    readonly COMMENT_NODE?: number | undefined;
    readonly DOCUMENT_FRAGMENT_NODE?: number | undefined;
    readonly DOCUMENT_NODE?: number | undefined;
    readonly DOCUMENT_POSITION_CONTAINED_BY?: number | undefined;
    readonly DOCUMENT_POSITION_CONTAINS?: number | undefined;
    readonly DOCUMENT_POSITION_DISCONNECTED?: number | undefined;
    readonly DOCUMENT_POSITION_FOLLOWING?: number | undefined;
    readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC?: number | undefined;
    readonly DOCUMENT_POSITION_PRECEDING?: number | undefined;
    readonly DOCUMENT_TYPE_NODE?: number | undefined;
    readonly ELEMENT_NODE?: number | undefined;
    readonly ENTITY_NODE?: number | undefined;
    readonly ENTITY_REFERENCE_NODE?: number | undefined;
    readonly NOTATION_NODE?: number | undefined;
    readonly PROCESSING_INSTRUCTION_NODE?: number | undefined;
    readonly TEXT_NODE?: number | undefined;
    dispatchEvent?: ((event: Event) => boolean) | undefined;
    animate?: ((keyframes: Keyframe[] | PropertyIndexedKeyframes | null, options?: number | KeyframeAnimationOptions | undefined) => Animation) | undefined;
    getAnimations?: (() => Animation[]) | undefined;
    after?: ((...nodes: (string | Node)[]) => void) | undefined;
    before?: ((...nodes: (string | Node)[]) => void) | undefined;
    remove?: (() => void) | undefined;
    replaceWith?: ((...nodes: (string | Node)[]) => void) | undefined;
    innerHTML?: string | undefined;
    readonly nextElementSibling?: Element | null | undefined;
    readonly previousElementSibling?: Element | null | undefined;
    readonly childElementCount?: number | undefined;
    readonly children?: HTMLCollection | undefined;
    readonly firstElementChild?: Element | null | undefined;
    readonly lastElementChild?: Element | null | undefined;
    append?: ((...nodes: (string | Node)[]) => void) | undefined;
    prepend?: ((...nodes: (string | Node)[]) => void) | undefined;
    querySelector?: {
        <K_6 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(selectors: K_6): HTMLElementTagNameMap[K_6] | null;
        <K_7 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(selectors: K_7): SVGElementTagNameMap[K_7] | null;
        <E_1 extends Element = Element>(selectors: string): E_1 | null;
    } | undefined;
    querySelectorAll?: {
        <K_8 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(selectors: K_8): NodeListOf<HTMLElementTagNameMap[K_8]>;
        <K_9 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(selectors: K_9): NodeListOf<SVGElementTagNameMap[K_9]>;
        <E_2 extends Element = Element>(selectors: string): NodeListOf<E_2>;
    } | undefined;
    oncopy?: ((this: DocumentAndElementEventHandlers, ev: ClipboardEvent) => any) | null | undefined;
    oncut?: ((this: DocumentAndElementEventHandlers, ev: ClipboardEvent) => any) | null | undefined;
    onpaste?: ((this: DocumentAndElementEventHandlers, ev: ClipboardEvent) => any) | null | undefined;
    readonly style?: CSSStyleDeclaration | undefined;
    contentEditable?: string | undefined;
    inputMode?: string | undefined;
    readonly isContentEditable?: boolean | undefined;
    onabort?: ((this: GlobalEventHandlers, ev: UIEvent) => any) | null | undefined;
    onanimationcancel?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onanimationend?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onanimationiteration?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onanimationstart?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onauxclick?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onblur?: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null | undefined;
    oncancel?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oncanplay?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oncanplaythrough?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onchange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onclick?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onclose?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oncontextmenu?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    oncuechange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ondblclick?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    ondrag?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragend?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragenter?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragexit?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ondragleave?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragover?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragstart?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondrop?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondurationchange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onemptied?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onended?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onerror?: OnErrorEventHandlerNonNull | null | undefined;
    onfocus?: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null | undefined;
    ongotpointercapture?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    oninput?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oninvalid?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onkeydown?: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null | undefined;
    onkeypress?: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null | undefined;
    onkeyup?: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null | undefined;
    onload?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onloadeddata?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onloadedmetadata?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onloadstart?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onlostpointercapture?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onmousedown?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseenter?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseleave?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmousemove?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseout?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseover?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseup?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onpause?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onplay?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onplaying?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onpointercancel?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerdown?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerenter?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerleave?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointermove?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerout?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerover?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerup?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onprogress?: ((this: GlobalEventHandlers, ev: ProgressEvent<EventTarget>) => any) | null | undefined;
    onratechange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onreset?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onresize?: ((this: GlobalEventHandlers, ev: UIEvent) => any) | null | undefined;
    onscroll?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onsecuritypolicyviolation?: ((this: GlobalEventHandlers, ev: SecurityPolicyViolationEvent) => any) | null | undefined;
    onseeked?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onseeking?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onselect?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onselectionchange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onselectstart?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onstalled?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onsubmit?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onsuspend?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ontimeupdate?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ontoggle?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ontouchcancel?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchend?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchmove?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchstart?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontransitioncancel?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    ontransitionend?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    ontransitionrun?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    ontransitionstart?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    onvolumechange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onwaiting?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onwheel?: ((this: GlobalEventHandlers, ev: WheelEvent) => any) | null | undefined;
    autofocus?: boolean | undefined;
    readonly dataset?: DOMStringMap | undefined;
    nonce?: string | undefined;
    tabIndex?: number | undefined;
    blur?: (() => void) | undefined;
    focus?: ((options?: FocusOptions | undefined) => void) | undefined;
    readonly sheet?: CSSStyleSheet | null | undefined;
} | {
    media?: string | undefined;
    type?: string | undefined;
    addEventListener?: {
        <K_10 extends "input" | "progress" | "select" | "reset" | "error" | "cancel" | "click" | "fullscreenchange" | "fullscreenerror" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | "auxclick" | "blur" | "canplay" | "canplaythrough" | "change" | "close" | "contextmenu" | "cuechange" | "dblclick" | "drag" | "dragend" | "dragenter" | "dragexit" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "ended" | "focus" | "focusin" | "focusout" | "gotpointercapture" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadstart" | "lostpointercapture" | "mousedown" | "mouseenter" | "mouseleave" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "pause" | "play" | "playing" | "pointercancel" | "pointerdown" | "pointerenter" | "pointerleave" | "pointermove" | "pointerout" | "pointerover" | "pointerup" | "ratechange" | "resize" | "scroll" | "securitypolicyviolation" | "seeked" | "seeking" | "selectionchange" | "selectstart" | "stalled" | "submit" | "suspend" | "timeupdate" | "toggle" | "touchcancel" | "touchend" | "touchmove" | "touchstart" | "transitioncancel" | "transitionend" | "transitionrun" | "transitionstart" | "volumechange" | "waiting" | "wheel" | "copy" | "cut" | "paste">(type: K_10, listener: (this: HTMLStyleElement, ev: HTMLElementEventMap[K_10]) => any, options?: boolean | AddEventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void;
    } | undefined;
    removeEventListener?: {
        <K_11 extends "input" | "progress" | "select" | "reset" | "error" | "cancel" | "click" | "fullscreenchange" | "fullscreenerror" | "abort" | "animationcancel" | "animationend" | "animationiteration" | "animationstart" | "auxclick" | "blur" | "canplay" | "canplaythrough" | "change" | "close" | "contextmenu" | "cuechange" | "dblclick" | "drag" | "dragend" | "dragenter" | "dragexit" | "dragleave" | "dragover" | "dragstart" | "drop" | "durationchange" | "emptied" | "ended" | "focus" | "focusin" | "focusout" | "gotpointercapture" | "invalid" | "keydown" | "keypress" | "keyup" | "load" | "loadeddata" | "loadedmetadata" | "loadstart" | "lostpointercapture" | "mousedown" | "mouseenter" | "mouseleave" | "mousemove" | "mouseout" | "mouseover" | "mouseup" | "pause" | "play" | "playing" | "pointercancel" | "pointerdown" | "pointerenter" | "pointerleave" | "pointermove" | "pointerout" | "pointerover" | "pointerup" | "ratechange" | "resize" | "scroll" | "securitypolicyviolation" | "seeked" | "seeking" | "selectionchange" | "selectstart" | "stalled" | "submit" | "suspend" | "timeupdate" | "toggle" | "touchcancel" | "touchend" | "touchmove" | "touchstart" | "transitioncancel" | "transitionend" | "transitionrun" | "transitionstart" | "volumechange" | "waiting" | "wheel" | "copy" | "cut" | "paste">(type: K_11, listener: (this: HTMLStyleElement, ev: HTMLElementEventMap[K_11]) => any, options?: boolean | EventListenerOptions | undefined): void;
        (type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions | undefined): void;
    } | undefined;
    accessKey?: string | undefined;
    readonly accessKeyLabel?: string | undefined;
    autocapitalize?: string | undefined;
    dir?: string | undefined;
    draggable?: boolean | undefined;
    hidden?: boolean | undefined;
    innerText?: string | undefined;
    lang?: string | undefined;
    readonly offsetHeight?: number | undefined;
    readonly offsetLeft?: number | undefined;
    readonly offsetParent?: Element | null | undefined;
    readonly offsetTop?: number | undefined;
    readonly offsetWidth?: number | undefined;
    spellcheck?: boolean | undefined;
    title?: string | undefined;
    translate?: boolean | undefined;
    click?: (() => void) | undefined;
    readonly assignedSlot?: HTMLSlotElement | null | undefined;
    readonly attributes?: NamedNodeMap | undefined;
    readonly classList?: DOMTokenList | undefined;
    className?: string | undefined;
    readonly clientHeight?: number | undefined;
    readonly clientLeft?: number | undefined;
    readonly clientTop?: number | undefined;
    readonly clientWidth?: number | undefined;
    id?: string | undefined;
    readonly localName?: string | undefined;
    readonly namespaceURI?: string | null | undefined;
    onfullscreenchange?: ((this: Element, ev: Event) => any) | null | undefined;
    onfullscreenerror?: ((this: Element, ev: Event) => any) | null | undefined;
    outerHTML?: string | undefined;
    readonly ownerDocument?: Document | undefined;
    readonly prefix?: string | null | undefined;
    readonly scrollHeight?: number | undefined;
    scrollLeft?: number | undefined;
    scrollTop?: number | undefined;
    readonly scrollWidth?: number | undefined;
    readonly shadowRoot?: ShadowRoot | null | undefined;
    slot?: string | undefined;
    readonly tagName?: string | undefined;
    attachShadow?: ((init: ShadowRootInit) => ShadowRoot) | undefined;
    closest?: {
        <K_2 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(selector: K_2): HTMLElementTagNameMap[K_2] | null;
        <K_3 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(selector: K_3): SVGElementTagNameMap[K_3] | null;
        <E extends Element = Element>(selector: string): E | null;
    } | undefined;
    getAttribute?: ((qualifiedName: string) => string | null) | undefined;
    getAttributeNS?: ((namespace: string | null, localName: string) => string | null) | undefined;
    getAttributeNames?: (() => string[]) | undefined;
    getAttributeNode?: ((name: string) => Attr | null) | undefined;
    getAttributeNodeNS?: ((namespaceURI: string, localName: string) => Attr | null) | undefined;
    getBoundingClientRect?: (() => DOMRect) | undefined;
    getClientRects?: (() => DOMRectList) | undefined;
    getElementsByClassName?: ((classNames: string) => HTMLCollectionOf<Element>) | undefined;
    getElementsByTagName?: {
        <K_4 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(qualifiedName: K_4): HTMLCollectionOf<HTMLElementTagNameMap[K_4]>;
        <K_5 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(qualifiedName: K_5): HTMLCollectionOf<SVGElementTagNameMap[K_5]>;
        (qualifiedName: string): HTMLCollectionOf<Element>;
    } | undefined;
    getElementsByTagNameNS?: {
        (namespaceURI: "http://www.w3.org/1999/xhtml", localName: string): HTMLCollectionOf<HTMLElement>;
        (namespaceURI: "http://www.w3.org/2000/svg", localName: string): HTMLCollectionOf<SVGElement>;
        (namespaceURI: string, localName: string): HTMLCollectionOf<Element>;
    } | undefined;
    hasAttribute?: ((qualifiedName: string) => boolean) | undefined;
    hasAttributeNS?: ((namespace: string | null, localName: string) => boolean) | undefined;
    hasAttributes?: (() => boolean) | undefined;
    hasPointerCapture?: ((pointerId: number) => boolean) | undefined;
    insertAdjacentElement?: ((position: InsertPosition, insertedElement: Element) => Element | null) | undefined;
    insertAdjacentHTML?: ((where: InsertPosition, html: string) => void) | undefined;
    insertAdjacentText?: ((where: InsertPosition, text: string) => void) | undefined;
    matches?: ((selectors: string) => boolean) | undefined;
    msGetRegionContent?: (() => any) | undefined;
    releasePointerCapture?: ((pointerId: number) => void) | undefined;
    removeAttribute?: ((qualifiedName: string) => void) | undefined;
    removeAttributeNS?: ((namespace: string | null, localName: string) => void) | undefined;
    removeAttributeNode?: ((attr: Attr) => Attr) | undefined;
    requestFullscreen?: ((options?: FullscreenOptions | undefined) => Promise<void>) | undefined;
    requestPointerLock?: (() => void) | undefined;
    scroll?: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    } | undefined;
    scrollBy?: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    } | undefined;
    scrollIntoView?: ((arg?: boolean | ScrollIntoViewOptions | undefined) => void) | undefined;
    scrollTo?: {
        (options?: ScrollToOptions | undefined): void;
        (x: number, y: number): void;
    } | undefined;
    setAttribute?: ((qualifiedName: string, value: string) => void) | undefined;
    setAttributeNS?: ((namespace: string | null, qualifiedName: string, value: string) => void) | undefined;
    setAttributeNode?: ((attr: Attr) => Attr | null) | undefined;
    setAttributeNodeNS?: ((attr: Attr) => Attr | null) | undefined;
    setPointerCapture?: ((pointerId: number) => void) | undefined;
    toggleAttribute?: ((qualifiedName: string, force?: boolean | undefined) => boolean) | undefined;
    webkitMatchesSelector?: ((selectors: string) => boolean) | undefined;
    readonly baseURI?: string | undefined;
    readonly childNodes?: NodeListOf<ChildNode> | undefined;
    readonly firstChild?: ChildNode | null | undefined;
    readonly isConnected?: boolean | undefined;
    readonly lastChild?: ChildNode | null | undefined;
    readonly nextSibling?: ChildNode | null | undefined;
    readonly nodeName?: string | undefined;
    readonly nodeType?: number | undefined;
    nodeValue?: string | null | undefined;
    readonly parentElement?: HTMLElement | null | undefined;
    readonly parentNode?: (Node & ParentNode) | null | undefined;
    readonly previousSibling?: ChildNode | null | undefined;
    textContent?: string | null | undefined;
    appendChild?: (<T extends Node>(newChild: T) => T) | undefined;
    cloneNode?: ((deep?: boolean | undefined) => Node) | undefined;
    compareDocumentPosition?: ((other: Node) => number) | undefined;
    contains?: ((other: Node | null) => boolean) | undefined;
    getRootNode?: ((options?: GetRootNodeOptions | undefined) => Node) | undefined;
    hasChildNodes?: (() => boolean) | undefined;
    insertBefore?: (<T_1 extends Node>(newChild: T_1, refChild: Node | null) => T_1) | undefined;
    isDefaultNamespace?: ((namespace: string | null) => boolean) | undefined;
    isEqualNode?: ((otherNode: Node | null) => boolean) | undefined;
    isSameNode?: ((otherNode: Node | null) => boolean) | undefined;
    lookupNamespaceURI?: ((prefix: string | null) => string | null) | undefined;
    lookupPrefix?: ((namespace: string | null) => string | null) | undefined;
    normalize?: (() => void) | undefined;
    removeChild?: (<T_2 extends Node>(oldChild: T_2) => T_2) | undefined;
    replaceChild?: (<T_3 extends Node>(newChild: Node, oldChild: T_3) => T_3) | undefined;
    readonly ATTRIBUTE_NODE?: number | undefined;
    readonly CDATA_SECTION_NODE?: number | undefined;
    readonly COMMENT_NODE?: number | undefined;
    readonly DOCUMENT_FRAGMENT_NODE?: number | undefined;
    readonly DOCUMENT_NODE?: number | undefined;
    readonly DOCUMENT_POSITION_CONTAINED_BY?: number | undefined;
    readonly DOCUMENT_POSITION_CONTAINS?: number | undefined;
    readonly DOCUMENT_POSITION_DISCONNECTED?: number | undefined;
    readonly DOCUMENT_POSITION_FOLLOWING?: number | undefined;
    readonly DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC?: number | undefined;
    readonly DOCUMENT_POSITION_PRECEDING?: number | undefined;
    readonly DOCUMENT_TYPE_NODE?: number | undefined;
    readonly ELEMENT_NODE?: number | undefined;
    readonly ENTITY_NODE?: number | undefined;
    readonly ENTITY_REFERENCE_NODE?: number | undefined;
    readonly NOTATION_NODE?: number | undefined;
    readonly PROCESSING_INSTRUCTION_NODE?: number | undefined;
    readonly TEXT_NODE?: number | undefined;
    dispatchEvent?: ((event: Event) => boolean) | undefined;
    animate?: ((keyframes: Keyframe[] | PropertyIndexedKeyframes | null, options?: number | KeyframeAnimationOptions | undefined) => Animation) | undefined;
    getAnimations?: (() => Animation[]) | undefined;
    after?: ((...nodes: (string | Node)[]) => void) | undefined;
    before?: ((...nodes: (string | Node)[]) => void) | undefined;
    remove?: (() => void) | undefined;
    replaceWith?: ((...nodes: (string | Node)[]) => void) | undefined;
    innerHTML?: string | undefined;
    readonly nextElementSibling?: Element | null | undefined;
    readonly previousElementSibling?: Element | null | undefined;
    readonly childElementCount?: number | undefined;
    readonly children?: HTMLCollection | undefined;
    readonly firstElementChild?: Element | null | undefined;
    readonly lastElementChild?: Element | null | undefined;
    append?: ((...nodes: (string | Node)[]) => void) | undefined;
    prepend?: ((...nodes: (string | Node)[]) => void) | undefined;
    querySelector?: {
        <K_6 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(selectors: K_6): HTMLElementTagNameMap[K_6] | null;
        <K_7 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(selectors: K_7): SVGElementTagNameMap[K_7] | null;
        <E_1 extends Element = Element>(selectors: string): E_1 | null;
    } | undefined;
    querySelectorAll?: {
        <K_8 extends "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "blockquote" | "body" | "br" | "button" | "canvas" | "caption" | "cite" | "code" | "col" | "colgroup" | "data" | "datalist" | "dd" | "del" | "details" | "dfn" | "dialog" | "div" | "dl" | "dt" | "em" | "embed" | "fieldset" | "figcaption" | "figure" | "footer" | "form" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "head" | "header" | "hgroup" | "hr" | "html" | "i" | "iframe" | "img" | "input" | "ins" | "kbd" | "label" | "legend" | "li" | "link" | "main" | "map" | "mark" | "menu" | "meta" | "meter" | "nav" | "noscript" | "ol" | "optgroup" | "option" | "output" | "p" | "param" | "picture" | "pre" | "progress" | "q" | "rp" | "rt" | "ruby" | "s" | "samp" | "slot" | "script" | "section" | "select" | "small" | "source" | "span" | "strong" | "style" | "sub" | "summary" | "sup" | "table" | "template" | "tbody" | "td" | "textarea" | "tfoot" | "th" | "thead" | "time" | "title" | "tr" | "track" | "u" | "ul" | "var" | "video" | "wbr" | "applet" | "basefont" | "dir" | "font" | "frame" | "frameset" | "marquee">(selectors: K_8): NodeListOf<HTMLElementTagNameMap[K_8]>;
        <K_9 extends "symbol" | "a" | "script" | "style" | "title" | "svg" | "circle" | "clipPath" | "defs" | "desc" | "ellipse" | "feBlend" | "feColorMatrix" | "feComponentTransfer" | "feComposite" | "feConvolveMatrix" | "feDiffuseLighting" | "feDisplacementMap" | "feDistantLight" | "feFlood" | "feFuncA" | "feFuncB" | "feFuncG" | "feFuncR" | "feGaussianBlur" | "feImage" | "feMerge" | "feMergeNode" | "feMorphology" | "feOffset" | "fePointLight" | "feSpecularLighting" | "feSpotLight" | "feTile" | "feTurbulence" | "filter" | "foreignObject" | "g" | "image" | "line" | "linearGradient" | "marker" | "mask" | "metadata" | "path" | "pattern" | "polygon" | "polyline" | "radialGradient" | "rect" | "stop" | "switch" | "text" | "textPath" | "tspan" | "use" | "view">(selectors: K_9): NodeListOf<SVGElementTagNameMap[K_9]>;
        <E_2 extends Element = Element>(selectors: string): NodeListOf<E_2>;
    } | undefined;
    oncopy?: ((this: DocumentAndElementEventHandlers, ev: ClipboardEvent) => any) | null | undefined;
    oncut?: ((this: DocumentAndElementEventHandlers, ev: ClipboardEvent) => any) | null | undefined;
    onpaste?: ((this: DocumentAndElementEventHandlers, ev: ClipboardEvent) => any) | null | undefined;
    readonly style?: CSSStyleDeclaration | undefined;
    contentEditable?: string | undefined;
    inputMode?: string | undefined;
    readonly isContentEditable?: boolean | undefined;
    onabort?: ((this: GlobalEventHandlers, ev: UIEvent) => any) | null | undefined;
    onanimationcancel?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onanimationend?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onanimationiteration?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onanimationstart?: ((this: GlobalEventHandlers, ev: AnimationEvent) => any) | null | undefined;
    onauxclick?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onblur?: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null | undefined;
    oncancel?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oncanplay?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oncanplaythrough?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onchange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onclick?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onclose?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oncontextmenu?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    oncuechange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ondblclick?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    ondrag?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragend?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragenter?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragexit?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ondragleave?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragover?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondragstart?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondrop?: ((this: GlobalEventHandlers, ev: DragEvent) => any) | null | undefined;
    ondurationchange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onemptied?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onended?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onerror?: OnErrorEventHandlerNonNull | null | undefined;
    onfocus?: ((this: GlobalEventHandlers, ev: FocusEvent) => any) | null | undefined;
    ongotpointercapture?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    oninput?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    oninvalid?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onkeydown?: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null | undefined;
    onkeypress?: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null | undefined;
    onkeyup?: ((this: GlobalEventHandlers, ev: KeyboardEvent) => any) | null | undefined;
    onload?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onloadeddata?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onloadedmetadata?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onloadstart?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onlostpointercapture?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onmousedown?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseenter?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseleave?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmousemove?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseout?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseover?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onmouseup?: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null | undefined;
    onpause?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onplay?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onplaying?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onpointercancel?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerdown?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerenter?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerleave?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointermove?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerout?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerover?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onpointerup?: ((this: GlobalEventHandlers, ev: PointerEvent) => any) | null | undefined;
    onprogress?: ((this: GlobalEventHandlers, ev: ProgressEvent<EventTarget>) => any) | null | undefined;
    onratechange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onreset?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onresize?: ((this: GlobalEventHandlers, ev: UIEvent) => any) | null | undefined;
    onscroll?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onsecuritypolicyviolation?: ((this: GlobalEventHandlers, ev: SecurityPolicyViolationEvent) => any) | null | undefined;
    onseeked?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onseeking?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onselect?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onselectionchange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onselectstart?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onstalled?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onsubmit?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onsuspend?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ontimeupdate?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ontoggle?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    ontouchcancel?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchend?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchmove?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontouchstart?: ((this: GlobalEventHandlers, ev: TouchEvent) => any) | null | undefined;
    ontransitioncancel?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    ontransitionend?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    ontransitionrun?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    ontransitionstart?: ((this: GlobalEventHandlers, ev: TransitionEvent) => any) | null | undefined;
    onvolumechange?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onwaiting?: ((this: GlobalEventHandlers, ev: Event) => any) | null | undefined;
    onwheel?: ((this: GlobalEventHandlers, ev: WheelEvent) => any) | null | undefined;
    autofocus?: boolean | undefined;
    readonly dataset?: DOMStringMap | undefined;
    nonce?: string | undefined;
    tabIndex?: number | undefined;
    blur?: (() => void) | undefined;
    focus?: ((options?: FocusOptions | undefined) => void) | undefined;
    readonly sheet?: CSSStyleSheet | null | undefined;
} | undefined) => [boolean, ErrorEvent | null];
export default useStyle;
